---
title: "Gulf of Lion Map"
author: "Stephanie Hopkins"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: true
---

```{r setup, include=FALSE, fig.width=6, fig.height=6}

rm(list = ls())
gc()

knitr::opts_chunk$set(echo=TRUE, warning=FALSE, message=FALSE, results = "hide")

list.of.packages <- c("sf","data.table","tidyverse","cowplot","ggpattern","rworldmap","rworldxtra", "ggspatial","ggpubr")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)

library(sf)
library(data.table)
library(tidyverse)
library(cowplot) # To save figures
library(ggpattern) # For textured shape file
library(rworldmap) # For Mapping
library(ggspatial) # For North Arrow and Scale Bar
library(ggpubr) # Arrange figure

# To Replace with your file directory
dir <- "C:/Users/steph/Documents"

MEDISIS <- "/MEDISIS/Part2.Analysing.the.simulation.output/"

path <- paste(dir,MEDISIS,sep="")

```

# Set file Location and create custom legend theme

```{r themes}

text_theme <- theme(axis.title = element_blank(), axis.text.y = element_text(margin=margin(t=0,r=0,b=0,l=0), size = 15), axis.text.x.bottom = element_text(margin=margin(t=0,r=0,b=0,l=0), size = 15), strip.text = element_text(size=15), panel.spacing = unit(0.35, "cm"))

```

# Make map of the management area

```{r effort_management_units}

GSA_zones <- st_read(paste(path,"/Data/Shape.Files/GSA_EMU1 - Shapefiles/GSAs_simplified.shp",sep="")) %>% 
  st_transform(st_crs(4326))

GSA_zones.sf <- st_as_sf(GSA_zones) 

GSA7 <- filter(GSA_zones, SECT_COD == "GSA07")
GSA7.sf <- st_as_sf(GSA7)

EMU1 <- filter(GSA_zones, SECT_COD %in% c("GSA01", "GSA05", "GSA06", "GSA07"))

EMU1.sf <- st_sf(EMU1) 
EMU1.sf$EMU <- "EMU1"

worldMap <- st_as_sf(getMap(resolution = "high"))

# create world map using ggplot() function
Mediterranean_Map <- ggplot() +
  geom_sf(data=GSA_zones.sf, col="darkgrey", fill="Aliceblue") +
  geom_sf(data=EMU1.sf, aes(fill=EMU), col=NA) +
  geom_sf(data=GSA7.sf, aes(fill=SMU_NAME), col=NA, alpha=.3) +
  geom_sf(data=worldMap, col="#ae8f60", fill="#E1C699") +
  coord_sf(xlim = c(-5.6, 41.7761), ylim = c(30.26389, 47.28054), expand = 0) + # Force lon/lat extent
  scale_fill_manual(name = element_blank(), values = c("Skyblue", "#129793"), labels = c("Remaining Management Area", "Gulf of Lion (GSA 07)")) +
  theme_bw()+
  theme(legend.title = element_blank(), axis.ticks = element_blank(), legend.text = element_text(size = 12), legend.key.height = unit(0.38, 'cm'),legend.key.width = unit(0.75, 'cm'), legend.spacing = unit(0.001, 'cm'), legend.position="top", axis.text = element_blank())
  
Mediterranean_Map

```

# Load Spatial Closures

```{r spatial_closures}

GDL_extension <- "Extra/carto/shapefile/Europe_coastline_shapefile/"

GDL <- read_sf(paste(path, "/Data/Shape.Files/", GDL_extension, "GDL.shp", sep = ""))

GDL_crop <- st_crop(GDL, xmin=2.95, xmax=6.05, ymin=41.95, ymax=43.6)

rm(GDL)

grid <- read_sf(paste(path, "/Data/Shape.Files/", "Grid/grid.shp", sep = ""))

FRA <- read_sf(paste(path, "/Data/Shape.Files/", "FRA/FRAs_WGS84.shp", sep = ""))
FRA <- FRA[1,]

NewFRA_regulation <- read_sf(paste(path, "/Data/Shape.Files/", "NewFRA_regulation/boxPaca_polygon_4326.shp", sep = ""))

zone_90_100_simplified <- read_sf(paste(path, "/Data/Shape.Files/", "zone_90_100_simplified/zone_90_100_simplifiee_Visvalingram_0_05_deg_accroche_dm_polygon_4326.shp", sep = ""))

Offshore_closure_z1 <- read_sf(paste(path, "/Data/Shape.Files/", "Offshore_closures/zone1.shp", sep = ""))

Offshore_closure_z2 <- read_sf(paste(path, "/Data/Shape.Files/", "Offshore_closures/zone2.shp", sep = ""))

Offshore_closure_z3 <- read_sf(paste(path, "/Data/Shape.Files/", "Offshore_closures/zone3.shp", sep = ""))

# Group the Offshore_closures into one file
Offshore_permanent_spdf <- rbind(Offshore_closure_z1, Offshore_closure_z2, Offshore_closure_z3)

Offshore_closure_seasonal <- read_sf(paste(path, "/Data/Shape.Files/", "Offshore_closures/Offshore_closure_seasonal_final.shp", sep = ""))

# load zone files
continental_sf <- read_sf(paste(path, "/Data/Shape.Files/", "continental_sf.new.shp", sep = ""))
canyon_sf <- read_sf(paste(path, "/Data/Shape.Files/", "canyon_sf.new.shp", sep = ""))

```

# Create Spatial Points for Port of Calls

Because we are not interested in squares use the actual gps coords. These were pulled from:

For Grand du Roi, Sète, and Marseille:

https://latitude.to/map/fr/france/cities/ 

For all others:

https://www.toutendroit.com/en/article-le-grau-d-agde-1884412/ 
https://www.gps-latitude-longitude.com/gps-coordinates-of-port-la-nouvelle
https://www.countrycoordinate.com/city-port-de-bouc-france/

```{r main_ports}

Abbreviation <- c("GST", "XST", "CST", "GPV", "CMT", "XMA")
Name <- c("Grand-du-Roi", "Sete", "Le-Grau-d'Adge", "Port-la-Nouvelle", "Port-de-Bouc", "Marseille")
cell <- c("La43.5Lo4.1", "La43.35Lo3.6", "La43.25Lo3.4", "La43.0Lo3.05", "La43.4Lo4.9", "La43.25Lo5.35")                  
longitude <- c(4.13559, 3.69278, 3.447424, 3.043916, 4.985931, 5.38107)
latitude <- c(43.53881, 43.4028, 	43.282701, 43.021342, 43.405449, 43.29695)

Ports <- data.frame(Abbreviation, Name, cell, longitude, latitude)
head(Ports)

# convert Ports to an spatial points data.frame
Ports.wgs84 <- st_as_sf(Ports,coords = c("longitude", "latitude"), crs = st_crs(4326))

GPV.wgs84 <- subset(Ports.wgs84, Name == "Port-la-Nouvelle")
CST.wgs84 <- subset(Ports.wgs84, Name == "Le-Grau-d'Adge")
XST.wgs84 <- subset(Ports.wgs84, Name == "Sete")
GST.wgs84 <- subset(Ports.wgs84, Name == "Grand-du-Roi")
CMT.wgs84 <- subset(Ports.wgs84, Name == "Port-de-Bouc")
XMA.wgs84 <- subset(Ports.wgs84, Name == "Marseille")

```

# Create map of study area

```{r Gulf_of_Lion_map}

cols <- c("#003366" = str_wrap("Seasonal Offshore Extensions Applies to Gears: OTB, OTT, GNS, and LLS Seasonally (Oct-Dec) or allYear", 28),
          "#b2182b" = str_wrap("Offshore Permanent Closures Applies to Gears: OTB, OTT, GNS, LLS allYear", 28),
          "#FF33FF" = str_wrap("90-100 Isobaths Closures Applies to Gears: OTB and OTT Seasonally (Sept-Apr) or allYear", 28),
          "#614B00" = str_wrap("Northward Expansion of FRA Applies to Gears: OTB and OTT Seasonally (Nov-Apr) or allYear", 28))

cols2 <- ("#614B00" = str_wrap("Original Fishing Restricted Area [FRA] Boundaries Applies to Gears: OTB and OTT allYear", 28))
  
GoL.map <- ggplot() +
  geom_sf(data = continental_sf, 
          aes(fill = "#26abff"),
          alpha = 0.3) +
  geom_sf(data = canyon_sf,
          aes(fill = "#c51b7d"),
          alpha = 0.3) +
  geom_sf(data = grid, 
          color = "grey") +
  geom_sf(data = zone_90_100_simplified,
          aes(color = "#FF33FF"),
          fill = "transparent", 
          linewidth = 0.5) +
  geom_sf_pattern(data = FRA, 
                  aes(pattern_fill = "#614B00"), 
                  pattern_fill2 = "transparent", 
                  pattern_colour = "transparent", 
                  color = "#614B00", 
                  fill = "transparent", 
                  pattern_aspect_ratio = 1.8, 
                  linewidth = 0.5, 
                  pattern_spacing = 0.01) +
  geom_sf(data = NewFRA_regulation, 
          aes(color = "#614B00"), 
          fill = "transparent", 
          linewidth = 0.5) +
  geom_sf(data = Offshore_closure_seasonal,
          aes(color = "#003366"),
          fill = "transparent", 
          linewidth = 0.25) +
  geom_sf(data = Offshore_permanent_spdf, 
                  aes(color = "#b2182b"), 
                  fill = "transparent", 
                  linewidth = 0.5) +
  scale_fill_identity(name = "Population Zones",
                      labels = c("#26abff" = str_wrap("Continental Shelf", 28), 
                                 "#c51b7d" = str_wrap("Interface of The Continental Shelf Break and Submarine Canyon Heads", 28)), 
                      guide = guide_legend("fill")) +
  scale_color_identity(name = "Closure Measures", 
                       labels = cols,
                       guide = guide_legend("color")) +
  scale_pattern_fill_identity(name = element_blank(), 
                              labels = cols2,
                              guide = guide_legend("pattern_fill"))+ 
  guides(fill = guide_legend(override.aes = list(alpha=0.3)), 
         color = guide_legend(order = 1), 
         pattern_fill = guide_legend(order = 2)) +
  geom_sf(data = GDL_crop, 
          color = "#ae8f60", 
          size = 0.7, 
          fill = "#E1C699") +
  geom_sf(data = GPV.wgs84, size = 1) +
  geom_sf_text(data = GPV.wgs84, 
               aes(label = Abbreviation),
               size = 3.5, 
               color = "black",
               nudge_x = -0.02,
               nudge_y = 0.04) +
  geom_sf(data = CST.wgs84, size = 1) +
  geom_sf_text(data = CST.wgs84, 
               aes(label = paste0(Name, " (", Abbreviation, ")", sep = '')),
               size = 3.5, 
               color = "black", 
               nudge_x = -0.18,
               nudge_y = 0.04) +
  geom_sf(data = XST.wgs84, size = 1) +
  geom_sf_text(data = XST.wgs84, 
               aes(label = paste0(Name, " (", Abbreviation, ")", sep = '')),
               size = 3.5, 
               color = "black", 
               nudge_x = -0.10, 
               nudge_y = 0.04) +
  geom_sf(data = GST.wgs84, size = 1) +
  geom_sf_text(data = GST.wgs84, 
               aes(label = paste0(Name, " (", Abbreviation, ")", sep = '')),
               size = 3.5, 
               color = "black", 
               nudge_x = -0.01,
               nudge_y = 0.04) +
  geom_sf(data = CMT.wgs84, size = 1) +
  geom_sf_text(data = CMT.wgs84, 
               aes(label = paste0(Name, " (", Abbreviation, ")", sep = '')),
               size = 3.5, 
               color = "black", 
               nudge_x = 0.05,
               nudge_y = 0.04) +
  geom_sf(data = XMA.wgs84, size = 1) +
  geom_sf_text(data = XMA.wgs84 , 
               aes(label = paste0(Name, " (", Abbreviation, ")", sep = '')),
               size = 3.5, 
               color = "black", 
               nudge_x = 0.20,
               nudge_y = 0.04) +
  annotation_scale(location = "br", 
                   pad_x = unit(0.85, "cm"),
                   pad_y = unit(0.5, "cm"),
                   text_cex = 1,
                   tick_height = 0.9)+ 
  annotation_north_arrow(location = "tl", 
                         which_north = "true", 
                         height = unit(1, "cm"), 
                         width = unit(1, "cm"), 
                         pad_x = unit(1.25, "cm"), 
                         pad_y = unit(0.75, "cm")) +
  theme_bw() +
  text_theme + 
  theme(legend.title = element_blank(), legend.text = element_text(size = 12),
        legend.margin = margin(t=-1,r=0, l=0, b=-1,'cm'), legend.spacing = unit(2, 'cm'),
        legend.position="left", legend.box = "vertical", 
        legend.key.height = unit(1.52, 'cm'), legend.key.width = unit(1.5, 'cm'))
  
GoL.map

```

# Figure 1

```{r Figure1}

Map_GoL <- ggarrange(Mediterranean_Map,
                     GoL.map,
                     ncol=1,nrow=2,align="hv",
                     widths=c(1,1),heights=c(0.35,0.65),
                     common.legend=FALSE,
                     hjust=0,vjust=1.5)
                     
Map_GoL

ggsave2(filename="Figure1.pdf",plot=Map_GoL, device="pdf", path=paste(path, "Figures/", sep=""), dpi=1200, width = 29.7, height = 21, unit="cm", limitsize = FALSE)

```

